language: objective-c
osx_image: xcode9.1

cache:
  - bundler
  - cocoapods

env:
  global:
  - WORKSPACE=Example/TPPDF.xcworkspace
  - PROJECT=Example/TPPDF.xcodeproj
  - TEST_FRAMEWORK_SCHEME="TPPDF-Example"
  - EXAMPLE_SCHEME="TPPDF-Example"
  - SOURCE_FOLDER="Source"
  matrix:
     - DESTINATION="OS=8.4,name=iPhone 6 Plus"
     - DESTINATION="OS=9.3,name=iPhone 6s Plus"
     - DESTINATION="OS=10.2,name=iPhone 7 Plus"
     - DESTINATION="OS=11.1,name=iPhone 8"
  
install:
  - bundle install
  - bundle exec pod repo update --silent
  - bundle exec pod install --project-directory=Example  

script:
  - set -o pipefail
  - xcodebuild -version
  - xcodebuild -showsdks
  - xcodebuild -list
  - xcodebuild -workspace "$WORKSPACE" -scheme "$TEST_FRAMEWORK_SCHEME" -sdk iphonesimulator -destination "$DESTINATION" -configuration Debug -derivedDataPath ${TRAVIS_BUILD_DIR}/derived_data  -enableCodeCoverage YES ONLY_ACTIVE_ARCH=YES GCC_INSTRUMENT_PROGRAM_FLOW_ARCS=YES GCC_GENERATE_TEST_COVERAGE_FILES=YES build test | xcpretty
  - xcodebuild -workspace "$WORKSPACE" -scheme "$EXAMPLE_SCHEME"        -sdk iphonesimulator -destination "$DESTINATION" -configuration Debug -derivedDataPath ${TRAVIS_BUILD_DIR}/derived_data                          ONLY_ACTIVE_ARCH=YES                                                                           build      | xcpretty
  - pod lib lint --allow-warnings
 
after_success:
  - slather coverage -t --build-directory ${TRAVIS_BUILD_DIR}/derived_data -s --verbose
  - bash <(curl -s https://codecov.io/bash) -f cobertura.xml -X coveragepy -X gcov -X xcode
